import type { Metadata } from 'next';
import { Teko } from 'next/font/google';
import { getAssetPath } from '@/utils/paths';
import './globals.css';
import ScrollToTopButton from '@/app/components/ScrollToTopButton/ScrollToTopButton';
import CartProvider from './Carrinho/cart';
import FavoritesProvider from './Favoritos/favorites';

const teko = Teko({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-teko',
});

export const metadata: Metadata = {
  title: 'Ideal Uniformes | Equipamentos Militares ',
  description: 'Generated by create next app',
  icons: {
    icon: getAssetPath('/logo-ideal.svg'),
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={teko.variable}>
      <body className="antialiased">
        <CartProvider>
          <FavoritesProvider>
            {children}
            <ScrollToTopButton />
          </FavoritesProvider>
        </CartProvider>
      </body>
    </html>
  );
}
