import React from 'react';
import type { Metadata } from 'next';
import { Teko } from 'next/font/google';
import { getAssetPath } from '@/utils/paths';
import './globals.css';
import CartProvider from './Carrinho/cart';
import FavoritesProvider from './Favoritos/favorites';

// Logs removidos para produção

const teko = Teko({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-teko',
});

export const metadata: Metadata = {
  title: 'Ideal Fardamentos | Equipamentos Militares ',
  description: 'Generated by create next app',
  icons: {
    icon: getAssetPath('/logo-ideal.svg'),
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={teko.variable}>
      <head>
        <script dangerouslySetInnerHTML={{
          __html: `
            window.addEventListener('DOMContentLoaded', function() {
              const rootStyles = getComputedStyle(document.documentElement);
              const cssLoaded = rootStyles.getPropertyValue('--debug-css-loaded');
              
              // Verificar se estilos dos módulos estão aplicados (não logando em console)
              setTimeout(() => {
                const headerEl = document.querySelector('[data-name="main-header"]');
                const footerEl = document.querySelector('[data-name="main-footer"]');
                if (headerEl) {
                  // headerEl exists; debugging info removed
                }
                if (footerEl) {
                  // footerEl exists; debugging info removed
                }
              }, 1000);
            });
          `
        }} />
      </head>
      <body className="antialiased">
        <React.Suspense fallback={null}>
          <CartProvider>
            <FavoritesProvider>
              {children}
            </FavoritesProvider>
          </CartProvider>
        </React.Suspense>
      </body>
    </html>
  );
}
