import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Ideal Uniformes | Equipamentos Militares ",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-ideal.svg"
  }
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="antialiased">{children}</body>
    </html>
  );
}
